CaravanMVC/Models/Registrar.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using Model;

namespace CaravanMVC.Models
{
    public class Registrar
    {
        private Usuario_VO objUsuario_VO;

        public Registrar()
        {
            objUsuario_VO = new Usuario_VO();
        }

        [Display(Name = "Nome")]
        [Required(ErrorMessage = "Informe o nome do usuário", AllowEmptyStrings = false)]
        public string Nome
        {
            get { return objUsuario_VO.Nome; }
            set { objUsuario_VO.Nome = value; }
        }

        [Required(ErrorMessage = "Informe o cpf", AllowEmptyStrings = false)]
        public string Cpf
        {
            get { return objUsuario_VO.Cpf; }
            set { objUsuario_VO.Cpf = value; }
        }

        [Required(ErrorMessage = "Informe o cpf", AllowEmptyStrings = false)]
        public string Email
        {
            get { return objUsuario_VO.Email; }
            set { objUsuario_VO.Email = value; }
        }

        [Required(ErrorMessage = "Informe a senha do usuário", AllowEmptyStrings = false)]
        [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
        public string Senha
        {
            get { return objUsuario_VO.Senha; }
            set { objUsuario_VO.Senha = value; }
        }

        public Usuario_VO UsuarioModel
        {
            get { return this.objUsuario_VO; }
        }

        public List<Registrar> Registrar_Collection = new List<Registrar>();
    }
}

CaravanMVC/Controllers/ContatoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CaravanMVC.Controllers
{
    public class ContatoController : Controller
    {
        // GET: Contato
        public ActionResult Index()
        {
            return View();
        }
    }
}

CaravanMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CaravanMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

CaravanMVC/Controllers/LocalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CaravanMVC.Controllers
{
    public class LocalController : Controller
    {
        // GET: Local
        public ActionResult California()
        {
            return View();
        }

        public ActionResult Dublin()
        {
            return View();
        }

        public ActionResult Paris()
        {
            return View();
        }
    }
}

CaravanMVC/Controllers/PlanoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CaravanMVC.Controllers
{
    public class PlanoController : Controller
    {
        // GET: Plano
        public ActionResult Index()
        {
            return View();
        }
    }
}

CaravanMVC/Controllers/RegistrarController.cs
using CaravanMVC.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using CaravanBLL;
using Model;

namespace CaravanMVC.Controllers
{
    public class RegistrarController : Controller
    {
        Usuario objUsuario;

        // GET: Registrar
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Registrar(Registrar registro) 
        {
            try
            {
                if (ModelState.IsValid)
                {
                    objUsuario = new Usuario();


                    //chamar a BLL para cadastrar
                    objUsuario.Registrar(registro.UsuarioModel);


                    ModelState.Clear();
                    registro = null;
                }
                return View("Index", registro);
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
    }
}

CaravanMVC/Views/Contato/Index.cshtml
    <section class="container">
        <div class="my-5 text-center">
            <span class="h6 d-block">POSSUI ALGUMA DÚVIDA?</span>
            <h2 class="display-4 text-primary">Fale Conosco</h2>
        </div>
        <div class="row">
            <div class="col-lg mb-5">
                <form class="bg-light rounded p-4 box-shadow">
                    <div class="form-group">
                        <label for="clienteNome">Nome</label>
                        <input type="text" class="form-control" id="clienteNome">
                    </div>
                    <div class="form-group">
                        <label for="clienteEmail">Email</label>
                        <input type="email" class="form-control" id="clienteEmail">
                    </div>
                    <div class="form-group">
                        <label for="clienteMensagem">Mensagem</label>
                        <textarea class="form-control" id="clienteMensagem" rows="4"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Enviar</button>
                </form>
            </div>
            <div class="col-lg">
                <h2 class="h6">NOSSO ENDEREÇO</h2>
                <a href="#">
                    <img src="/Content/Images/mapa.png" alt="Endereço da empresa" class="img-fluid box-shadow rounded mb-4">
                </a>

                <h2 class="h6">DADOS DE CONTATO</h2>
                <ul class="list-unstyled text-secondary">
                    <li>caravan@caravan.com.br</li>
                    <li>21 99999-9999</li>
                    <li>De Seg. à Sex. das 8h às 18h</li>
                </ul>

                <h2 class="h6">REDES SOCIAIS</h2>
                <ul class="list-unstyled" style="max-width: 260px">
                    <li><a href="#" class="btn btn-outline-secondary btn-block mb-2 btn-sm">Facebook</a></li>
                    <li><a href="#" class="btn btn-outline-secondary btn-block mb-2 btn-sm">Twitter</a></li>
                    <li><a href="#" class="btn btn-outline-secondary btn-block mb-2 btn-sm">Youtube</a></li>
                </ul>
            </div>
        </div>
    </section>

    <section class="container">
        <div class="my-5 text-center">
            <span class="h6 d-block">AINDA ESTÁ COM DÚVIDAS?</span>
            <h2 class="display-4 text-primary">Perguntas Frequentes</h2>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-6" id="perguntasFrequentes" data-children=".pergunta">
                <div class="pergunta py-2">
                    <a href="#pergunta1" class="lead" data-toggle="collapse" ria-expanded="true" aria-controls="pergunta1">→ É possível cancelar a viagem?</a>
                    <div id="pergunta1" class="collapse show" role="tabpanel" data-parent="#perguntasFrequentes">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pretium lorem non vestibulum scelerisque. Proin a vestibulum sem, eget tristique massa. Aliquam lacinia rhoncus nibh quis ornare.</p>
                    </div>
                </div>
                <div class="dropdown-divider"></div>
                <div class="pergunta py-2">
                    <a href="#pergunta2" class="lead" data-toggle="collapse" ria-expanded="true" aria-controls="pergunta2">→ Qual a garantia que tenho se perder o voo?</a>
                    <div id="pergunta2" class="collapse" role="tabpanel" data-parent="#perguntasFrequentes">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pretium lorem non vestibulum scelerisque. Proin a vestibulum sem, eget tristique massa. Aliquam lacinia rhoncus nibh quis ornare.</p>
                    </div>
                </div>
                <div class="dropdown-divider"></div>
                <div class="pergunta py-2">
                    <a href="#pergunta3" class="lead" data-toggle="collapse" ria-expanded="true" aria-controls="pergunta3">→ Qual a principal forma de viagem?</a>
                    <div id="pergunta3" class="collapse" role="tabpanel" data-parent="#perguntasFrequentes">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pretium lorem non vestibulum scelerisque. Proin a vestibulum sem, eget tristique massa. Aliquam lacinia rhoncus nibh quis ornare.</p>
                    </div>
                </div>
                <div class="dropdown-divider"></div>
                <div class="pergunta py-2">
                    <a href="#pergunta4" class="lead" data-toggle="collapse" ria-expanded="true" aria-controls="pergunta4">→ Qual o melhor destino de viagem?</a>
                    <div id="pergunta4" class="collapse" role="tabpanel" data-parent="#perguntasFrequentes">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pretium lorem non vestibulum scelerisque. Proin a vestibulum sem, eget tristique massa. Aliquam lacinia rhoncus nibh quis ornare.</p>
                    </div>
                </div>
                <div class="dropdown-divider"></div>
                <div class="pergunta py-2">
                    <a href="#pergunta5" class="lead" data-toggle="collapse" ria-expanded="true" aria-controls="pergunta5">→ Vocês dão descontos para grupos grandes?</a>
                    <div id="pergunta5" class="collapse" role="tabpanel" data-parent="#perguntasFrequentes">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pretium lorem non vestibulum scelerisque. Proin a vestibulum sem, eget tristique massa. Aliquam lacinia rhoncus nibh quis ornare.</p>
                    </div>
                </div>
                <div class="dropdown-divider"></div>
            </div>
        </div>
        <div class="text-center my-4">
            <p class="small m-1">FALE CONOSCO PARA MAIS DÚVIDAS</p>
            <a href="contato.html" class="btn btn-primary">Entre em Contato</a>
        </div>
    </section>
                                                                                                                     

CaravanMVC/Views/Home/Index.cshtml
    <section class="container-fluid">
        <div class="row bg-dark text-white">

            <div class="col-lg-7 p-0">
                <div id="carouselCidades" class="carousel slide" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselCidades" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselCidades" data-slide-to="1"></li>
                        <li data-target="#carouselCidades" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner">
                        <div class="carousel-item active">
                            <img class="d-block w-100" src="~/Content/Images/california.jpg" alt="California">
                            <div class="carousel-caption"><H3 class="display-4">California</H3></div>
                        </div>
                        <div class="carousel-item">
                            <img class="d-block w-100" src="~/Content/Images/paris.jpg" alt="Paris">
                            <div class="carousel-caption"><H3 class="display-4">Paris</H3></div>
                        </div>
                        <div class="carousel-item">
                            <img class="d-block w-100" src="~/Content/Images/dublin.jpg" alt="Dublin">
                            <div class="carousel-caption"><H3 class="display-4">Dublin</H3></div>
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselCidades" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Anterior</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselCidades" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Próximo</span>
                    </a>
                </div>
            </div>

            <div class="col-lg-5 p-4 align-self-center">
                <h1 class="display-4">Realize a viagem do seu sonho</h1>
                <p class="lead">O melhor local para viajar é com a Caravan, mais de 5.000 excursões concluídas</p>
                <form action="">
                    <div class="input-group input-group-lg">
                        <input type="text" class="form-control" placeholder="E-mail" aria-label="E-mail" aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="button">Inscreva-se</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section>

    <section class="py-5 bg-light text-center">
        <div class="container">
            <div class="my-5">
                <span class="h6 d-block">TUDO DE MELHOR PARA VOCÊ</span>
                <h2 class="display-4 text-primary">Aproveite as Vantagens</h2>
            </div>

            <div class="row">
                <div class="col-xl-4 col-md-6">
                    <div style="height: 100px;" class="d-flex justify-content-center">
                        <img src="~/Content/Images/icones/passaporte.svg" alt="Passaporte">
                    </div>
                    <h3>Documentos</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo, nemo nulla.</p>
                </div>

                <div class="col-xl-4 col-md-6">
                    <div style="height: 100px;" class="d-flex justify-content-center">
                        <img src="/Content/Images/icones/passagens.svg" alt="Passagens">
                    </div>
                    <h3>Passagens</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo, nemo nulla.</p>
                </div>

                <div class="col-xl-4 col-md-6">
                    <div style="height: 100px;" class="d-flex justify-content-center">
                        <img src="/Content/Images/icones/translado.svg" alt="Translado">
                    </div>
                    <h3>Translado</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo, nemo nulla.</p>
                </div>

                <div class="col-xl-4 col-md-6">
                    <div style="height: 100px;" class="d-flex justify-content-center">
                        <img src="/Content/Images/icones/praias.svg" alt="Praias">
                    </div>
                    <h3>Praias</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo, nemo nulla.</p>
                </div>

                <div class="col-xl-4 col-md-6">
                    <div style="height: 100px;" class="d-flex justify-content-center">
                        <img src="/Content/Images/icones/bagagens.svg" alt="Bagagens">
                    </div>
                    <h3>Bagagens</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo, nemo nulla.</p>
                </div>

                <div class="col-xl-4 col-md-6">
                    <div style="height: 100px;" class="d-flex justify-content-center">
                        <img src="/Content/Images/icones/turismo.svg" alt="Turismo">
                    </div>
                    <h3>Turismo</h3>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Illo, nemo nulla.</p>
                </div>
            </div>

            <a href="planos.html" class="btn btn-primary btn-lg mt-4">Comprar Plano</a>

        </div>
    </section>






    <section id="home-quote" class="p-md-5">
        <blockquote class="blockquote text-center text-white p-md-5 p-3">
            <p class="display-4 "><em>"A felicidade não está na estrada que leva a algum lugar. A felicidade é a própria estrada."</em></p>
            <footer class="blockquote-footer text-white">Bob Dylan</footer>
        </blockquote>
    </section>






    <section class="container">
        <div class="my-5 text-center">
            <span class="h6 d-block">AINDA ESTÁ COM DÚVIDAS?</span>
            <h2 class="display-4 text-primary">Perguntas Frequentes</h2>
        </div>
        <div class="row justify-content-center">
            <div class="col-md-6" id="perguntasFrequentes" data-children=".pergunta">
                <div class="pergunta py-2">
                    <a href="#pergunta1" class="lead" data-toggle="collapse" ria-expanded="true" aria-controls="pergunta1">→ É possível cancelar a viagem?</a>
                    <div id="pergunta1" class="collapse show" role="tabpanel" data-parent="#perguntasFrequentes">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pretium lorem non vestibulum scelerisque. Proin a vestibulum sem, eget tristique massa. Aliquam lacinia rhoncus nibh quis ornare.</p>
                    </div>
                </div>
                <div class="dropdown-divider"></div>
                <div class="pergunta py-2">
                    <a href="#pergunta2" class="lead" data-toggle="collapse" ria-expanded="true" aria-controls="pergunta2">→ Qual a garantia que tenho se perder o voo?</a>
                    <div id="pergunta2" class="collapse" role="tabpanel" data-parent="#perguntasFrequentes">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pretium lorem non vestibulum scelerisque. Proin a vestibulum sem, eget tristique massa. Aliquam lacinia rhoncus nibh quis ornare.</p>
                    </div>
                </div>
                <div class="dropdown-divider"></div>
                <div class="pergunta py-2">
                    <a href="#pergunta3" class="lead" data-toggle="collapse" ria-expanded="true" aria-controls="pergunta3">→ Qual a principal forma de viagem?</a>
                    <div id="pergunta3" class="collapse" role="tabpanel" data-parent="#perguntasFrequentes">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pretium lorem non vestibulum scelerisque. Proin a vestibulum sem, eget tristique massa. Aliquam lacinia rhoncus nibh quis ornare.</p>
                    </div>
                </div>
                <div class="dropdown-divider"></div>
                <div class="pergunta py-2">
                    <a href="#pergunta4" class="lead" data-toggle="collapse" ria-expanded="true" aria-controls="pergunta4">→ Qual o melhor destino de viagem?</a>
                    <div id="pergunta4" class="collapse" role="tabpanel" data-parent="#perguntasFrequentes">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pretium lorem non vestibulum scelerisque. Proin a vestibulum sem, eget tristique massa. Aliquam lacinia rhoncus nibh quis ornare.</p>
                    </div>
                </div>
                <div class="dropdown-divider"></div>
                <div class="pergunta py-2">
                    <a href="#pergunta5" class="lead" data-toggle="collapse" ria-expanded="true" aria-controls="pergunta5">→ Vocês dão descontos para grupos grandes?</a>
                    <div id="pergunta5" class="collapse" role="tabpanel" data-parent="#perguntasFrequentes">
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed pretium lorem non vestibulum scelerisque. Proin a vestibulum sem, eget tristique massa. Aliquam lacinia rhoncus nibh quis ornare.</p>
                    </div>
                </div>
                <div class="dropdown-divider"></div>
            </div>
        </div>
        <div class="text-center my-4">
            <p class="small m-1">FALE CONOSCO PARA MAIS DÚVIDAS</p>
            <a href="contato.html" class="btn btn-primary">Entre em Contato</a>
        </div>
    </section>
                                    

CaravanMVC/Views/Local/California.cshtml
    <section class="container">
        <div class="text-center my-5">
            <span class="h6 d-block">O MELHOR DESTINO DA SUA VIDA</span>
            <h2 class="display-4 text-primary">Descubra Dublin</h2>
        </div>
        <div class="row">
            <div class="col-md">
                <img src="~/Content/Images/local/foto-1.jpg" alt="Foto 1" class="img-fluid mb-4">
                <img src="~/Content/Images/local/foto-2.jpg" alt="Foto 2" class="img-fluid mb-4">
                <img src="~/Content/Images/local/foto-3.jpg" alt="Foto 3" class="img-fluid mb-4">
            </div>
            <div class="col-md">
                <img src="~/Content/Images/local/foto-4.jpg" alt="Foto 4" class="img-fluid mb-4">
                <img src="~/Content/Images/local/foto-5.jpg" alt="Foto 5" class="img-fluid mb-4">
            </div>
            <div class="col-md">
                <img src="~/Content/Images/local/foto-6.jpg" alt="Foto 6" class="img-fluid mb-4">
                <img src="~/Content/Images/local/foto-7.jpg" alt="Foto 7" class="img-fluid mb-4">
            </div>
        </div>
    </section>

    <section class="container">
        <div class="text-center my-5">
            <span class="h6 d-block">DESCUBRA O QUE ACONTECEU NA CIDADE</span>
            <h2 class="display-4 text-primary">Próximos Eventos</h2>
        </div>
        <table class="table table-hover-responsive-md">
            <thead>
                <tr>
                    <th scope="col">Data</th>
                    <th scope="col">Evento</th>
                    <th scope="col">Local</th>
                    <th scope="col">Ticket</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">23/10</th>
                    <td>Julien Baker</td>
                    <td>The Academy</td>
                    <td><a href="#" class="btn btn-outline-primary btn-sm">Comprar Ticket </a></td>
                </tr>
                <tr>
                    <th scope="row">23/10</th>
                    <td>Julien Baker</td>
                    <td>The Academy</td>
                    <td><a href="#" class="btn btn-outline-primary btn-sm">Comprar Ticket </a></td>
                </tr>
                <tr>
                    <th scope="row">23/10</th>
                    <td>Julien Baker</td>
                    <td>The Academy</td>
                    <td><a href="#" class="btn btn-outline-primary btn-sm">Comprar Ticket </a></td>
                </tr>
            </tbody>
        </table>
    </section>

                                                                                                                       

CaravanMVC/Views/Local/Dublin.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
    
    </div>
</body>
</html>

CaravanMVC/Views/Local/Paris.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
    
    </div>
</body>
</html>

CaravanMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title>Caravan</title>
    @Styles.Render("~/Content/css")
</head>
<body>

    <!-- Modal -->
    <div class="modal fade" id="modalLogin" tabindex="-1" role="dialog" aria-labelledby="ModalLoginTitulo" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="ModalLoginTitulo">Entre na Sua Conta</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form>
                        <div class="form-group">
                            <label for="loginEmail">Email</label>
                            <input type="email" class="form-control" id="loginEmail">
                        </div>
                        <div class="form-group">
                            <label for="loginSenha">Senha</label>
                            <input type="password" class="form-control" id="loginSenha">
                        </div>
                        <button type="submit" class="btn btn-primary">Entrar na conta</button>
                        <small class="form-text text-muted">Esqueceu a senha? <a href="#">Clique aqui.</a></small>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- AQUI JAZ O MODAL-->

    <nav class="navbar navbar-expand-md navbar-light bg-light fixed-top p-3 box-shadow">
        <a class="navbar-brand" href="/">
            <img src="~/Content/Images/caravan.svg" alt="Caravan">
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Abrir navegação">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Locais</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        @Html.ActionLink("California", "California", "Local", new { area = "" }, new { @class = "dropdown-item" })
                        @Html.ActionLink("Paris", "California", "Local", new { area = "" }, new { @class = "dropdown-item" })
                        @Html.ActionLink("Dublin", "California", "Local", new { area = "" }, new { @class = "dropdown-item" })
                    </div>
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Planos", "Index", "Plano", new { area = "" }, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Contato", "Index", "Contato", new { area = "" }, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#" data-toggle="modal" data-target="#modalLogin">Login</a>
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Inscreva-se", "Index", "Registrar", new { area = "" }, new { @class = "btn btn-primary ml-md-2" })
                </li>
            </ul>
        </div>
    </nav>
    
    @RenderBody()

    <footer class="bg-dark text-white mt-5">
        <div class="container py-4">
            <div class="row">
                <div class="col-md-3 col-6">
                    <h4 class="h6">PÁGINAS</h4>
                    <ul class="list-unstyled">
                        <li>@Html.ActionLink("Planos", "Index", "Plano")</li>
                        <li>@Html.ActionLink("Contatos", "Index", "Contato")</li>
                        <li>@Html.ActionLink("Inscreva-se", "Index", "Registrar")</li>
                    </ul>
                </div>
                <div class="col-md-3 col-6">
                    <h4 class="h6">Locais</h4>
                    <ul class="list-unstyled">
                        <li>@Html.ActionLink("California", "California", "Local")</li>
                        <li>@Html.ActionLink("Paris", "California", "Local")</li>
                        <li>@Html.ActionLink("Dublin", "California", "Local")</li>
                    </ul>
                </div>
                <div class="col-md-4">
                    <h4 class="h6">DADOS DE CONTATO</h4>
                    <ul class="list-unstyled text-secondary">
                        <li>gabryelwapnyk@gmail.com</li>
                        <li>11 95806-7640</li>
                        <li>De Seg. à Sex. das 8h às 18h</li>
                    </ul>
                </div>
                <div class="col-md-2">
                    <h4 class="h6">REDES SOCIAIS</h4>
                    <ul class="list-unstyled">
                        <li><a href="https://www.facebook.com" class="btn btn-outline-secondary btn-block mb-2 btn-sm" style="max-width: 140px;">Facebook</a></li>
                        <li><a href="https://www.linkedin.com/in/gabryel-wapnyk-b81a081a4/" class="btn btn-outline-secondary btn-block mb-2 btn-sm" style="max-width: 140px;">Linkedin</a></li>
                        <li><a href="https://github.com/gwapnyk" class="btn btn-outline-secondary btn-block mb-2 btn-sm" style="max-width: 140px;">Github</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="bg-primary text-center py-3">
            <p class="mb-0">Caravan © 2017. Alguns direitos reservados.</p>
        </div>
    </footer>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/popper")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/app")
    @RenderSection("scripts", required: false)
</body>
</html>